# Generated by Django 4.0.5 on 2022-06-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='time_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='time_created',
            new_name='date_created',
        ),
    ]
